### ISSUE TITLE
access to variable types

### ISSUE THREAD

**Issue by mlubin** [dpo/AmplNLReader.jl#10]
I wasn't able to find out how to access the counts of the variable types (Tables 3 and 4 in [hooking your solver to AMPL](http://ampl.com/REFS/hooking2.pdf)). Are these currently exposed?

**Comment by dpo** [comment]
They're not currently exposed. I'll have a look.

**Comment by mlubin** [comment]
Thanks! I'm trying to read in some MINLP test problems.

**Comment by dpo** [comment]
This involves changes to `AmplNLReader`, `NLP` (in `MathProgBase`) and `mp` itself. To build:

* check out the [`vartypes` branch](https://github.com/dpo/mp/tree/vartypes) of my `mp` fork, build it, install somewhere and point your `LD_LIBRARY_PATH` to that location (better remove previous installs of `mp`)
* check out the [`vartypes` branch](https://github.com/dpo/MathProgBase.jl/tree/vartypes) of my `MathProgBase` fork
* check out the [`vartypes` branch](https://github.com/dpo/AmplNLReader.jl/tree/vartypes) of `AmplNLReader`.

I haven't checked that the values are correct yet. The field names are the same as in AMPL (i.e., not intelligible). Perhaps they should be changed, but it's nice to follow the *Hooking* document.

**Comment by mlubin** [comment]
Cool! Did you push your local vartypes branch to ``MathProgBase``? I don't see the changes.

Mirroring AMPL's unintelligible names in the NLP data structure is perhaps an indication that this data structure is a bit of a leaky abstraction and might better fit in ``AmplNLReader`` instead of in ``MathProgBase``, but let's not hold up this feature request with possible restructuring.

**Comment by dpo** [comment]
Oops. Done.

**Comment by mlubin** [comment]
Tested this out and seemed to give reasonable answers. Thanks!

While we're touching ``aslinterface.c``, could I also request access to ``nlo`` so that we can detect if an objective is linear? (ref https://github.com/mlubin/AMPLMathProgInterface.jl/issues/1)

**Comment by dpo** [comment]
Should be done. Pull all 3 branches.

**Comment by mlubin** [comment]
Tested and appears to be working
